import type { TravelContentStore } from "@/lib/content/types";

export const defaultTravelContentStore: TravelContentStore = {
  tours: [
    {
      id: "hunza-spring-2026",
      slug: "northern-pakistan-adventure",
      title: "Northern Pakistan Adventure",
      region: "Pakistan",
      destination: "Hunza, Skardu & Fairy Meadows",
      durationDays: 8,
      startDateISO: "2026-04-05",
      endDateISO: "2026-04-12",
      departureCity: "Lahore",
      seatsLeft: 6,
      status: "active",
      highlights: ["Attabad Lake", "Khunjerab Pass", "Baltit Fort"],
      price: "₨85,000",
      originalPrice: "₨95,000",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop",
      features: ["Accommodation", "Transportation", "Meals", "Guide", "Sightseeing"],
      rating: 4.9,
      reviews: 127,
      discount: "10% OFF",
      isFeatured: true,
    },
    {
      id: "dubai-eid-2026",
      slug: "dubai-luxury-experience",
      title: "Dubai Luxury Experience",
      region: "UAE",
      destination: "Dubai, UAE",
      durationDays: 5,
      startDateISO: "2026-04-20",
      endDateISO: "2026-04-24",
      departureCity: "Karachi",
      seatsLeft: 9,
      status: "active",
      highlights: ["Burj Khalifa", "Palm Jumeirah", "Dubai Mall"],
      price: "₨120,000",
      originalPrice: "₨135,000",
      image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=600&fit=crop",
      features: ["5-Star Hotel", "Desert Safari", "City Tours", "Flights", "Breakfast"],
      rating: 4.8,
      reviews: 89,
      discount: "11% OFF",
      isFeatured: true,
    },
    {
      id: "turkey-summer-2026",
      slug: "turkey-cultural-journey",
      title: "Turkey Cultural Journey",
      region: "Turkey",
      destination: "Istanbul & Cappadocia",
      durationDays: 7,
      startDateISO: "2026-05-10",
      endDateISO: "2026-05-16",
      departureCity: "Islamabad",
      seatsLeft: 4,
      status: "active",
      highlights: ["Hagia Sophia", "Cappadocia", "Bosphorus Cruise"],
      price: "₨150,000",
      originalPrice: "₨165,000",
      image: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&h=600&fit=crop",
      features: ["Hotels", "Hot Air Balloon", "Tours", "Transfers", "Meals"],
      rating: 4.9,
      reviews: 156,
      discount: "9% OFF",
      isFeatured: true,
    },
    {
      id: "maldives-summer-2026",
      slug: "maldives-paradise",
      title: "Maldives Paradise",
      region: "Maldives",
      destination: "Maldives Islands",
      durationDays: 6,
      startDateISO: "2026-05-25",
      endDateISO: "2026-05-30",
      departureCity: "Lahore",
      seatsLeft: 3,
      status: "active",
      highlights: ["Crystal Waters", "Coral Reefs", "Sunset Views"],
      price: "₨180,000",
      originalPrice: "₨200,000",
      image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop",
      features: ["Water Villa", "All Meals", "Snorkeling", "Transfers", "Spa"],
      rating: 5,
      reviews: 94,
      discount: "10% OFF",
      isFeatured: true,
    },
    {
      id: "thailand-discovery-2026",
      slug: "thailand-discovery",
      title: "Thailand Discovery",
      region: "Thailand",
      destination: "Bangkok & Phuket",
      durationDays: 6,
      startDateISO: "2026-06-12",
      endDateISO: "2026-06-17",
      departureCity: "Karachi",
      seatsLeft: 8,
      status: "upcoming",
      highlights: ["Grand Palace", "Phi Phi Islands", "Floating Market"],
      price: "₨95,000",
      originalPrice: "₨110,000",
      image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&h=600&fit=crop",
      features: ["Hotels", "Flights", "Tours", "Meals", "Transfers"],
      rating: 4.7,
      reviews: 203,
      discount: "14% OFF",
      isFeatured: true,
    },
    {
      id: "switzerland-alpine-2026",
      slug: "switzerland-alpine",
      title: "Switzerland Alpine",
      region: "Switzerland",
      destination: "Zurich, Interlaken & Lucerne",
      durationDays: 8,
      startDateISO: "2026-07-05",
      endDateISO: "2026-07-12",
      departureCity: "Islamabad",
      seatsLeft: 5,
      status: "upcoming",
      highlights: ["Jungfraujoch", "Lake Lucerne", "Swiss Alps"],
      price: "₨220,000",
      originalPrice: "₨245,000",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop",
      features: ["Hotels", "Train Pass", "Tours", "Breakfast", "Guide"],
      rating: 4.9,
      reviews: 78,
      discount: "10% OFF",
      isFeatured: true,
    },
  ],
  destinations: [
    {
      id: "northern-areas",
      slug: "northern-areas",
      name: "Northern Areas",
      country: "Pakistan",
      packages: "25+",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop",
      description: "Majestic mountains, crystal-clear lakes, and breathtaking valleys",
      startingFrom: "₨45,000",
    },
    {
      id: "dubai",
      slug: "dubai",
      name: "Dubai",
      country: "UAE",
      packages: "18+",
      image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=600&fit=crop",
      description: "Luxury shopping, stunning architecture, and desert adventures",
      startingFrom: "₨85,000",
    },
    {
      id: "turkey",
      slug: "turkey",
      name: "Turkey",
      country: "Turkey",
      packages: "22+",
      image: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&h=600&fit=crop",
      description: "Rich history, unique landscapes, and vibrant culture",
      startingFrom: "₨95,000",
    },
    {
      id: "maldives",
      slug: "maldives",
      name: "Maldives",
      country: "Maldives",
      packages: "15+",
      image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop",
      description: "Pristine beaches, turquoise waters, and luxury resorts",
      startingFrom: "₨150,000",
    },
    {
      id: "thailand",
      slug: "thailand",
      name: "Thailand",
      country: "Thailand",
      packages: "20+",
      image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&h=600&fit=crop",
      description: "Tropical paradise with rich culture and delicious cuisine",
      startingFrom: "₨65,000",
    },
    {
      id: "switzerland",
      slug: "switzerland",
      name: "Switzerland",
      country: "Switzerland",
      packages: "12+",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop",
      description: "Alpine beauty, charming cities, and world-class hospitality",
      startingFrom: "₨180,000",
    },
  ],
  testimonials: [
    {
      id: "ayesha-malik",
      name: "Ayesha Malik",
      role: "Travel Enthusiast",
      rating: 5,
      comment:
        "The Northern Pakistan tour exceeded all expectations! The guides were knowledgeable, accommodations were comfortable, and the scenery was absolutely breathtaking. Highly recommend!",
      image:
        "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face",
      tour: "Northern Pakistan Adventure",
      date: "March 2024",
    },
    {
      id: "hassan-ali",
      name: "Hassan Ali",
      role: "Photographer",
      rating: 5,
      comment:
        "Dubai Luxury package was worth every rupee! From the desert safari to the city tours, everything was perfectly organized. The hotel was amazing and the service was top-notch.",
      image:
        "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
      tour: "Dubai Luxury Experience",
      date: "February 2024",
    },
    {
      id: "fatima-khan",
      name: "Fatima Khan",
      role: "Travel Blogger",
      rating: 5,
      comment:
        "Turkey was magical! The hot air balloon ride in Cappadocia was a dream come true. The tour guides were friendly and the food was incredible. Can't wait to book another trip!",
      image:
        "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
      tour: "Turkey Cultural Journey",
      date: "January 2024",
    },
    {
      id: "ahmed-sheikh",
      name: "Ahmed Sheikh",
      role: "Business Executive",
      rating: 5,
      comment:
        "Maldives was paradise! The water villa was stunning, the food was excellent, and the snorkeling experience was unforgettable. Square Three Sixty made our honeymoon perfect!",
      image:
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
      tour: "Maldives Paradise",
      date: "December 2023",
    },
  ],
  ownerProfile: {
    name: "Hamza Tahir",
    title: "Founder & Head of Tours",
    bio: "With over 10 years crafting unforgettable journeys across Pakistan and beyond, I founded Square Three Sixty to share the world's hidden gems with passionate explorers like you.",
    badge: "Verified Guide",
    image: "/travel-tours/owner.jpg",
    stats: [
      { value: "10+", label: "Years Exp.", icon: "award" },
      { value: "5k+", label: "Travelers", icon: "users" },
      { value: "40+", label: "Destinations", icon: "mapPin" },
      { value: "300+", label: "Trips/Year", icon: "calendar" },
    ],
  },
  siteSettings: {
    promoBarText: "Exclusive deals on Pakistan & International tours",
    phone: "+92 300 1234567",
    email: "travel@square360.com",
    supportHours: "Mon-Sat 9AM-7PM",
    footerDescription:
      "Your journey starts here. Creating unforgettable travel experiences and memories that last a lifetime.",
    socialLinks: [
      { label: "LinkedIn", href: "#" },
      { label: "Twitter", href: "#" },
      { label: "Instagram", href: "#" },
    ],
    legalLinks: [
      { label: "Privacy Policy", href: "#" },
      { label: "Terms of Service", href: "#" },
    ],
  },
  travelFormOptions: {
    joiningCities: ["Lahore", "Karachi", "Islamabad", "Multan", "Peshawar"],
    packageTypes: ["Standard", "Deluxe", "Luxury", "Honeymoon", "Family"],
    placesToVisitOptions: [
      "City Tour",
      "Historical Sites",
      "Shopping",
      "Adventure Activities",
      "Boat/Desert Safari",
      "Museums",
      "Nature Spots",
    ],
    hotelsOptions: ["3-Star", "4-Star", "5-Star", "Resort", "Boutique Hotel"],
    vehiclesOptions: ["Sedan", "SUV", "Coaster", "Hiace", "Land Cruiser"],
  },
  inquiries: [],
};
